# Generated by Django 4.2.5 on 2023-09-21 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Bangladeshi mobile number in the format: '+8801XXXXXXXXX'.", regex='^\\+?8801[3-9]\\d{8}$')]),
        ),
    ]
